name: tudo_na_mao
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev



environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.3.0
  audioplayers: ^6.5.0
  shared_preferences: ^2.2.2
  workmanager: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  # Adicionar assets aqui se necessário
  # assets:
  #   - assets/sounds/